apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache
  namespace: web
  labels:
    app: httpd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: httpd:2.4.54

---

kubectl set image deployment.apps/apache httpd=alpine -n web
kubectl scale deployment apache --replicas=5 -n web