apiVersion: v1
kind: Pod
metadata:
  name: pod-multi
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  - name: busybox
    image: busybox:glibc
    command: ['sh', '-c', 'sleep 3600']