apiVersion: v1
kind: Pod
metadata:
  name: web-pod
  namespace: busybox
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command: ['sh', '-c', 'echo "Hello" && sleep 3600']
    securityContext:
      capabilities:
        add: ["SYS_TIME"]