apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web-pod
  name: web-pod
spec:
  containers:
    - image: busybox
      name: web-pod
      command: ["sleep", "3200"]
      securityContext:
        capabilities:
          add:
            - SYS_TIME
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
