apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: mysql
  labels:
    app: mysql
spec:
  selector:
    app: mysql
  ports:
  - port: 80

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: mysql
spec:
  selector:
    matchLabels:
      app: mysql 
  serviceName: "mysql-svc"
  replicas: 2 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:8.0.40-debian
        env:
          - name: MYSQL_USER 
            valueFrom:
              configMapKeyRef:
                name: configmap 
                key: MYSQL_USER
          - name: MYSQL_DATABASE 
            valueFrom:
              configMapKeyRef:
                name: configmap 
                key: MYSQL_DATABASE
          - name: MYSQL_ROOT_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: secret 
                key: MYSQL_ROOT_PASSWORD
          - name: MYSQL_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: secret 
                key: MYSQL_PASSWORD


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  namespace: mysql
data:
  POSTGRES_USER: "user"
  MYSQL_DATABASE: "database"

---

apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: mysql
stringData:
  MYSQL_ROOT_PASSWORD: "cm9vdA=="
  MYSQL_PASSWORD: "dXNlcg=="