apiVersion: v1
data:
  MYSQL_PASSWORD: dGVzdA==
  MYSQL_ROOT_PASSWORD: dGVzdA==
kind: Secret
metadata:
  creationTimestamp: null
  name: secret

---

apiVersion: v1
data:
  MYSQL_DATABASE: test
  MYSQL_USER: test
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: configmap

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:8.0.40-debian

        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: MYSQL_ROOT_PASSWORD

          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: secret
                key: MYSQL_PASSWORD

          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: MYSQL_DATABASE

          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: MYSQL_USER

        ports:
        - containerPort: 3306
          name: mysql-port