apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-data-pv
  namespace: q5
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Recycle
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd"