apiVersion: v1
kind: Pod
metadata:
  name: nginx-jaud00401
  labels:
    app: nginx-jaud00401
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    disk: ssd