apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres-service
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
  selector:
    app: postgres

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: "postgres-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres:13.16-bookworm

        env:
        - name: POSTGRES_PASSWORD
          value: "test"
        - name: POSTGRES_USER
          value: "test"
        - name: POSTGRES_DB
          value: "test"

        ports:
        - containerPort: 5432
          name: postgres-port